#+OPTIONS: H:4 num:nil toc:3
#+SETUPFILE: ~/git/org-html-themes/setup/theme-readtheorg.setup
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="kbd-style.css"/>

* 0.6.0
:PROPERTIES:
:CUSTOM_ID: 0.6.0
:END:
-----
** Fixes
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fixes
:END:
*** =swiper-avy= should use only the current window
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-swiper-avy-should-use-only-the-current-window
:END:
Not all windows. See [[https://github.com/abo-abo/swiper/issues/117][#117]].
-----
*** fix wrap-around for =ivy-next-line=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-fix-wrap-around-for-ivy-next-line
:END:
See [[https://github.com/abo-abo/swiper/issues/118][#118]].
-----
*** =swiper-avy= should do nothing for empty input
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-swiper-avy-should-do-nothing-for-empty-input
:END:
See [[https://github.com/abo-abo/avy/issues/50][#50]].
-----
*** =ivy-alt-done= should require TRAMP if necessary
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-ivy-alt-done-should-require-tramp-if-necessary
:END:
See [[https://github.com/abo-abo/swiper/pull/145][#145]].
-----
*** =swiper-query-replace= shouldn't miss the first occurrence
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-swiper-query-replace-shouldnt-miss-the-first-occurrence
:END:
See [[https://github.com/abo-abo/swiper/pull/144][#144]].
-----
*** =swiper= should not deactivate mark
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-swiper-should-not-deactivate-mark
:END:
*** =ivy-mode= should not switch to TRAMP for certain input
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-ivy-mode-should-not-switch-to-tramp-for-certain-input
:END:
See [[https://github.com/abo-abo/swiper/pull/145][#145]].
-----
*** =counsel-find-file= should work better with TRAMP
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-counsel-find-file-should-work-better-with-tramp
:END:
"/ssh:foo" should not be cut off
See [[https://github.com/abo-abo/swiper/pull/145][#145]].
-----
*** =counsel-find-file= supports Windows drive letters
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-counsel-find-file-supports-windows-drive-letters
:END:
See [[https://github.com/abo-abo/swiper/pull/155][#155]].
-----
*** =counsel-file-file= should work better with files that contain "~"
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-counsel-file-file-should-work-better-with-files-that-contain-
:END:
See [[https://github.com/abo-abo/swiper/pull/157][#157]].
-----
*** =counsel-M-x= should respect =ivy-format-function=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-counsel-m-x-should-respect-ivy-format-function
:END:
See [[https://github.com/abo-abo/swiper/pull/150][#150]].
-----
*** =counsel-git-grep= should position better on exit
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-counsel-git-grep-should-position-better-on-exit
:END:
See [[https://github.com/abo-abo/swiper/pull/153][#153]].
-----
*** =ivy-mode= should re-scale text to minibuffer height
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-ivy-mode-should-re-scale-text-to-minibuffer-height
:END:
See [[https://github.com/abo-abo/swiper/pull/151][#151]].
-----
*** =counsel-unicode-char= should use action-style call
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-counsel-unicode-char-should-use-action-style-call
:END:
See [[https://github.com/abo-abo/swiper/pull/160][#160]].
-----
*** =ivy-read= should allow % in prompt string
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-ivy-read-should-allow--in-prompt-string
:END:
See [[https://github.com/abo-abo/swiper/pull/171][#171]].
-----
*** =ivy-call= should execute in proper window
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-ivy-call-should-execute-in-proper-window
:END:
See [[https://github.com/abo-abo/swiper/pull/176][#176]].
** New Features
:PROPERTIES:
:CUSTOM_ID: 0-6-0-fx-new-features
:END:
*** =ivy-mode=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nf-ivy-mode
:END:
**** Open an Info file on the file system
When in =Info-mode=, press ~g~ and select either "(./)" or "(../)" to
switch to file name completion. That file will be opened with Info.
-----
**** Account for =minibuffer-depth-indication-mode=
If you have =minibuffer-depth-indication-mode= on, the minibuffer
prompt will indicate the current depth.
See [[https://github.com/abo-abo/swiper/pull/134][#134]].
-----
**** Add fuzzy matching function
To enable fuzzy matching, set your =ivy-re-builders-alist= accordingly:
#+begin_src elisp
(setq ivy-re-builders-alist
      '((t . ivy--regex-fuzzy)))
#+end_src
See [[https://github.com/abo-abo/swiper/pull/136][#136]].

See also [[https://github.com/abo-abo/swiper/pull/142][#142]] for toggling fuzzy matching with ~C-o m~.
-----
**** =case-fold-search= optimization
Bind case-fold-search to t when the input is all lower-case:

- input "the" matches both "the" and "The".
- input "The" matches only "The".

See [[https://github.com/abo-abo/swiper/pull/166][#166]].
-----
**** Allow to see the candidate index a la =anzu= via =ivy-count-format=
To have this feature, use something like this:
#+begin_src elisp
(setq ivy-count-format "(%d/%d) ")
#+end_src
See [[https://github.com/abo-abo/swiper/pull/167][#167]].

You can also set this to "", if you don't want any count, see [[https://github.com/abo-abo/swiper/pull/188][#188]].
-----
**** Allow to add additional exit points for any command
Example for =ivy-switch-to-buffer=:
#+begin_src elisp
(ivy-set-actions
 'ivy-switch-buffer
 '(("k"
    (lambda (x)
      (kill-buffer x)
      (ivy--reset-state ivy-last))
    "kill")
   ("j"
    ivy--switch-buffer-other-window-action
    "other")))
#+end_src

After this:

- use ~M-o k~ to kill a buffer
- use ~M-o j~ to switch to a buffer in other window

You can always use ~M-o o~ to access the default action. When there is
only one action, ~M-o~ does the same as ~C-m~.

See [[https://github.com/abo-abo/swiper/pull/164][#164]].








-----
*** =counsel-describe-function= and =counsel-decribe-variable=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nf-counsel-describe-function-and-counsel-decribe-variable
:END:
**** Add a binding to look up the symbol in info
Press ~C-,~ to look up the symbol in info, instead of the default
describe action.
See [[https://github.com/abo-abo/swiper/pull/121][#121]].
-----
**** Handle symbol-at-point better in non-Elisp buffers
See [[https://github.com/abo-abo/swiper/pull/126][#126]].
-----
*** =ivy-switch-buffer=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nf-ivy-switch-buffer
:END:
**** New face =ivy-virtual=
See [[https://github.com/abo-abo/swiper/pull/129][#129]].
-----
**** Deal better with invisible buffers
See [[https://github.com/abo-abo/swiper/pull/135][#135]].
-----
**** Add custom keymap
You can customize =ivy-switch-buffer-map=.

See [[https://github.com/abo-abo/swiper/pull/164][#164]].
-----
**** Add extra actions
Add a =kill-buffer= action, and =switch-to-buffer-other-window= action.
-----
*** =counsel-git-grep=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nf-counsel-git-grep
:END:
**** Add Async
Make it fully async: the process =git grep= will be killed and
restarted on new input. This results in almost no keyboard delay.
-----
**** Own history variable
*** =swiper=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nf-swiper
:END:
**** Own history variable
Having own history variable allows to get more use of ~M-p~, ~M-n~ and ~C-r~.
-----
*** =counsel-el=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nf-counsel-el
:END:
**** Switch to action-style call
This allows to make use of ~C-M-n~ and ~C-M-p~.
-----
*** =counsel-locate=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nf-counsel-locate
:END:
**** Add Async
**** Add extra actions
In addition to the default action of opening a file add:

- =xdg-open= action
- =dired= action

Press ~M-o~ or ~C-o~ to access these actions.
-----
**** Add own history

-----
*** API
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nf-api
:END:
**** Add :matcher
A matcher is a function that accepts a regexp and a list of candidates
and returns the filtered list of candidates.

The default matcher is basically =cl-remove-if-not= + =string-match=.
If you'd like to customize this, pass your own matcher.

See =counsel-git-grep-matcher= for an example.
-----
**** Allow to customize the initial input for all commands
Customize =ivy-initial-inputs-alist= for this.
See [[https://github.com/abo-abo/swiper/pull/140][#140]].
-----
**** =ivy-sort-functions-alist= should also examine =this-command=
**** :dynamic-collection is now a boolean
Pass the collection function as the second var instead.

** New Commands
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nf-new-commands
:END:
*** =ivy-call=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-ivy-call
:END:
Execute the current action for the current candidate without exiting
the minibuffer.  Bound to ~C-M-m~ or ~M-RET~ or ~C-o g~.


-----
*** =counsel-find-file=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-counsel-find-file
:END:
Forward to =find-file= with Ivy completion.

=ivy-next-line-and-call= as well as =ivy-resume= should work for this command.

The variable =counsel-find-file-ignore-regexp= allows to ignore
certain files, like dot files.  Input a leading dot to see all files.

The variable =counsel-find-file-at-point= allows to automatically use
=ffap=.  You also can do it manually with ~M-n~ when the point is on a file name.

The variable =counsel-find-file-map= allows to customize the
minibuffer key bindings for this command.

Recommended binding:

#+begin_src elisp
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
#+end_src

You can peek at files with ~C-M-n~ and ~C-M-p~.

See [[https://github.com/abo-abo/swiper/issues/122][#122]] and [[https://github.com/abo-abo/swiper/issues/123][#123]].

See [[https://github.com/abo-abo/swiper/pull/152][#152]] about ~M-n~, ~M-p~ and ~M-i~ switching directories when necessary.

-----
*** =ivy-recentf=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-ivy-recentf
:END:
Find a file on =recentf-list=.

Note that if your set =ivy-use-virtual-buffers=, =recentf-list= is
merged into candidates list for =ivy-switch-buffer=. But if you want
it separately, you can use this command.

See [[https://github.com/abo-abo/swiper/issues/124][#124]].
-----
*** =ivy-yank-word=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-ivy-yank-word
:END:
Add word at point to minibuffer input.

This is similar to what ~C-w~ does for =isearch=.  However it's bound
to ~M-j~ instead of ~C-w~, since ~C-w~ is bound to =kill-region= - a
useful command.

See [[https://github.com/abo-abo/swiper/issues/125][#125]].
-----
*** =counsel-M-x=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-counsel-m-x
:END:
Forward to =execute-extended-command= with Ivy completion.
The candidate list will also display the key binding for each bound command.

This command will piggyback on =smex= for sorting, if =smex= is installed.

Use =counsel-M-x-initial-input= to customize the initial input for
this command.  By default, it's "^" - the regex character that
indicates beginning of string.  This results in much faster matching,
since you usually type the command name from the start.

See [[https://github.com/abo-abo/swiper/pull/136][#136]] and [[https://github.com/abo-abo/swiper/pull/138][#138]].

-----
*** =hydra-ivy=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-hydra-ivy
:END:
Press ~C-o~ to toggle the Hydra for Ivy.
It gives access to shorter bindings and many customizable options.

Use ~C-o >~ to grow the minibuffer.
Use ~C-o <~ to shrink the minibuffer.

See [[https://github.com/abo-abo/swiper/pull/151][#151]].

-----
*** =ivy-toggle-calling=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-ivy-toggle-calling
:END:
Toggle executing the current action each time a new candidate is selected.

This command is bound to ~C-o c~.

To explain how this is useful: ~C-M-m C-M-f C-M-f C-M-f~  is equivalent to ~C-o cjjj~.

-----
*** =ivy-insert-current=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-ivy-insert-current
:END:
Inserts the current candidate into the minibuffer.

Press ~M-i~ if you want something close to the current candidate. You
can follow up with an edit and select.

I find this very useful when creating new files with a similar name to
the existing file: ~C-x C-f M-i~ + a bit of editing is very fast.

See [[https://github.com/abo-abo/swiper/pull/141][#141]].

-----
*** =counsel-load-theme=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-counsel-load-theme
:END:
Forward to =load-theme= with Ivy completion. Allows to rapidly try themes (e.g. with ~C-M-n~).

-----
*** =ivy-reverse-i-search=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-ivy-reverse-i-search
:END:
Allow to recursively match history with ~C-r~.

I like this command from bash shell. The usual way to search through
history is with ~M-p~ and ~M-n~.  Using =ivy-reverse-i-search= will
open a recursive completion session with the current history as the
candidates.
-----
*** =counsel-rhythmbox=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-counsel-rhythmbox
:END:
[[http://oremacs.com/2015/07/09/counsel-rhythmbox/][Control Rhythmbox from Emacs.]]
-----
*** =ivy-dispatching-done=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-ivy-dispatching-done
:END:
Select an action for the current candidate and execute it. Bound to ~M-o~.

Some commands that support ~M-o~:

- =counsel-rhythmbox=
- =counsel-describe-function=
- =counsel-describe-variable=
- =ivy-switch-buffer=
- =counsel-locate=

-----
*** =counsel-org-tag=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-counsel-org-tag
:END:
Forward to =org-set-tags= with Ivy completion.

Selecting any tag each time will toggle it on/off.
The current list of selected tags will be displayed in the prompt.

See [[https://github.com/abo-abo/swiper/pull/177][#177]] and [[https://github.com/abo-abo/swiper/pull/91][#91]].

-----
*** =counsel-org-tag-agenda=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-counsel-org-tag-agenda
:END:
Forward to =org-agenda-set-tags= with Ivy completion.
See [[https://github.com/abo-abo/swiper/pull/177][#177]].

-----
*** =counsel-ag=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-counsel-ag
:END:
Interactively =ag= using Ivy completion.

-----
*** =counsel-recoll=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-counsel-recoll
:END:
Use =recoll= with Ivy completion.
See [[http://oremacs.com/2015/07/27/counsel-recoll/][Using Recoll desktop search database with Emacs]].

Install recoll with =sudo apt-get install recoll=.

-----
*** =swiper-from-isearch=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-swiper-from-isearch
:END:
Start =swiper= from the current =isearch= input.

-----
*** =ivy-immediate-done=
:PROPERTIES:
:CUSTOM_ID: 0-6-0-nc-ivy-immediate-done
:END:
Use this command to exit the minibuffer choosing not the current
candidate, but the current text.  Bound to ~C-M-j~ or ~C-u C-j~.

See [[https://github.com/abo-abo/swiper/pull/183][#183]].

-----
* 0.7.0
:PROPERTIES:
:CUSTOM_ID: 0.7.0
:END:
-----
** Fixes
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fixes
:END:
*** Fix :dynamic-collection not being sorted
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-fix-dynamic-collection-not-being-sorted
:END:
*** When :initial-input contains a plus, escape it
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-when-initial-input-contains-a-plus,-escape-it
:END:
See [[https://github.com/abo-abo/swiper/issues/195][#195]].
-----
*** Set line-spacing to 0 in the minibuffer
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-set-line-spacing-to-0-in-the-minibuffer
:END:
See [[https://github.com/abo-abo/swiper/issues/198][#198]].
-----
*** Enlarge the minibuffer window if the candidate list doesn't fit
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-enlarge-the-minibuffer-window-if-the-candidate-list-doesnt-fit
:END:
See [[https://github.com/abo-abo/swiper/issues/198][#198]] and [[https://github.com/abo-abo/swiper/issues/161][#161]] and [[https://github.com/abo-abo/swiper/issues/220][#220]].
-----
*** Fix minibuffer collapsing to one line
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-fix-minibuffer-collapsing-to-one-line
:END:
See [[https://github.com/abo-abo/swiper/issues/237][#237]], [[https://github.com/abo-abo/swiper/issues/229][#229]] and [[https://github.com/abo-abo/swiper/issues/77][#77]].
-----
*** Use minibuffer-allow-text-properties
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-use-minibuffer-allow-text-properties
:END:
Allows =ivy-read= to return a propertized string.
-----
*** Improve ~C-g~ out of a long-running async process
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-improve-c-g-out-of-a-long-running-async-process
:END:
Use =counsel-delete-process= as =:unwind=.
-----
*** Don't regexp-quote :preselect
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-dont-regexp-quote-preselect
:END:
See [[https://github.com/abo-abo/swiper/issues/245][#245]].
-----
*** Fix ivy-partial for fuzzy completion
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-fix-ivy-partial-for-fuzzy-completion
:END:
See [[https://github.com/abo-abo/swiper/issues/266][#266]].
-----
*** ivy-resume should pass :caller
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-ivy-resume-should-pass-caller
:END:
See [[https://github.com/abo-abo/swiper/issues/245][#245]].
-----
*** Fix the regression in perfect match logic
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-fix-the-regression-in-perfect-match-logic
:END:
See [[https://github.com/abo-abo/swiper/issues/270][#270]].
-----
*** Fix pasting file paths on Windows
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-fix-pasting-file-paths-on-windows
:END:
*** ~C-j~ should no stop completion for a pasted file path
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-c-j-should-no-stop-completion-for-a-pasted-file-path
:END:
*** ~C-M-j~ should use =ivy--directory=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-c-m-j-should-use-ivy--directory
:END:
When completing file names, expand the file name properly.
See [[https://github.com/abo-abo/swiper/issues/275][#275]].
-----
*** Use a specific blend method for dark themes
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-use-a-specific-blend-method-for-dark-themes
:END:
See [[https://github.com/abo-abo/swiper/issues/278][#278]].
-----
*** Fix one-off bug in =ivy-scroll-up-command= and =ivy-scroll-down-command=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-fix-one-off-bug-in-ivy-scroll-up-command-and-ivy-scroll-down-command
:END:
*** ~M-o~ shouldn't set the action permanently
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-m-o-shouldnt-set-the-action-permanently
:END:
So now it's possible to e.g. =counsel-describe-function= -> ~M-o d~ ->
=ivy-resume= -> ~M-o o~ -> =ivy-resume= -> ~M-o i~.
-----
*** Fix swiper preselect issue with similar or identical lines
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-fix-swiper-preselect-issue-with-similar-or-identical-lines
:END:
See [[https://github.com/abo-abo/swiper/issues/290][#290]].
-----
*** Make ivy-completing-read handle history as cons
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-make-ivy-completing-read-handle-history-as-cons
:END:
See [[https://github.com/abo-abo/swiper/issues/295][#295]].
-----
*** Perform string-match in the original buffer
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-perform-string-match-in-the-original-buffer
:END:
The syntax for whitespace, separators etc. is different for modes.  See [[https://github.com/abo-abo/swiper/issues/298][#298]].
** New Features
:PROPERTIES:
:CUSTOM_ID: 0-7-0-fx-new-features
:END:
*** =swiper=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-swiper
:END:
**** Make line numbers into display properties
Each candidate is now a single space plus the original string.  The
display property of the single space holds the line number. This means
that it's no longer possible to match line numbers in queries, which
is a good thing if you're searching for numbers.
-----
**** Extend =swiper-font-lock-ensure=
Add =mu4e-view-mode=, =mu4e-headers-mode=, =help-mode=,
=elfeed-show-mode=, =emms-stream-mode=, =debbugs-gnu-mode=,
=occur-mode=, =occur-edit-mode=, =bongo-mode=, =eww-mode=, =vc-dir-mode=.
-----
**** Add support for =evil-jumper/backward=
See [[https://github.com/abo-abo/swiper/issues/268][#268]].
-----
**** Make compatible with =visual-line-mode=
=swiper= will split the lines when =visual-line-mode= is on.  This is
convenient for small buffers. For large buffers, it can be very slow,
since =visual-line-mode= is slow.
See [[https://github.com/abo-abo/swiper/issues/227][#227]].
-----
**** Add =swiper-toggle-face-matching=
Bound to ~C-c C-f~.
At each start of =swiper=, the face at point will be stored.
Use this command to toggle matching only the candidates with that face.
See [[https://github.com/abo-abo/swiper/issues/288][#288]].
-----
**** =push-mark= only if exited the minibuffer
~C-M-n~ and ~C-M-p~ will no longer push mark and annoy with messages.
-----
**** =ivy-resume= should restore the buffer for =swiper=
See [[https://github.com/abo-abo/swiper/issues/302][#302]].
-----
**** Enable recursive =swiper= calls
While you =swiper= buffer-1, you can switch out of the minibuffer into
buffer-2 and call =swiper= again.  Exiting the second minibuffer will
restore the first minibuffer.

To use this, you need to enable recursive minibuffers.
#+begin_src elisp
(setq enable-recursive-minibuffers t)
#+end_src

It's also useful to indicate the current depth:

#+begin_src elisp
(minibuffer-depth-indicate-mode 1)
#+end_src

See [[https://github.com/abo-abo/swiper/issues/309][#309]].
-----
**** Fix for =twittering-mode=
The =field= text property is now removed before inserting text into
the minibuffer. This fixes the =swiper= problems with
=twittering-mode=. See [[https://github.com/abo-abo/swiper/issues/310][#310]].




-----
*** =ivy=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-ivy
:END:
**** Add manual
In the current state, the manual covers the most basic topics, like
the minibuffer key bindings and the regexp builders.
-----
**** Make <left> and <right> behave as in fundamental-mode
**** Truncate minibuffer prompts longer than window-width
See [[https://github.com/abo-abo/swiper/issues/240][#240]].
-----
**** ~C-M-n~ should not leave the minibuffer
Make sure that the minibuffer window remains selected as long as the
completion hasn't finished.  For example, ~<f1> f~ to call
=counsel-describe-function=, input "forward" and spam ~C-M-n~ to read
the doc for each function that starts with "forward". The =*Help*=
window popup would move the window focus, but this change moves it
back to the minibuffer.
-----
**** Add =flx= sorting
See [[https://github.com/abo-abo/swiper/issues/207][#207]].
Since flx is costly, move the caching to an earlier point. This means
immediate return for when the input hasn't changed, i.e. for ~C-n~ or
~C-p~. When =flx= is installed, and =(eq ivy--regex-function 'ivy--regex-fuzzy)=
for current function (through =ivy-re-builders-alist=), then sort the final candidates with
=ivy--flx-sort=.

In the worst case, when some error pops up, return the same list. In
the best case sort the =cands= that all match =name= by closeness to
=name=.

How to use:
1. Have =flx= installed - =(require 'flx)= should succeed.
2. Configure =ivy-re-builders-alist= appropriately to use =ivy--regex-fuzzy=.

For example:

#+begin_src elisp
(setq ivy-re-builders-alist
      '((t . ivy--regex-fuzzy)))
#+end_src
-----
**** Support hash tables
Since =all-completions= also works for hash tables, no reason not to support them.
-----
**** Improve documentation of =ivy-count-format=
Now possible to set it with Customize.
-----
**** Add =ivy-index-functions-alist=
Customize this to decide how the index, i.e. the currently selected
candidate, is updated with new input.
For example, one strategy is not reset it to 0 after each change.

Another strategy, used for =swiper=, is to try to select the first
appropriate candidate after (inclusive) the first previously selected
candidate. This way, if you're typing something that matches what is
currently selected, the selection won't change.

See [[https://github.com/abo-abo/swiper/issues/253][#253]].
-----
**** Add =ivy-virtual-abbreviate=
The mode of abbreviation for virtual buffer names.
-----
**** Add =ivy-case-fold-search=
Used to override =case-fold-search=. See [[https://github.com/abo-abo/swiper/issues/259][#259]].
-----
**** Add feedback for long-running async processes
Each time 0.5s pass after the last input, if the external process
hasn't finished yet, update minibuffer with the amount of candidates
collected so far. This is useful to see that long running commands
like =counsel-locate= or =counsel-ag= (when in a very large directory)
aren't stuck.
-----
**** Promote =ivy-extra-directories= to defcustom
**** Promote =ivy-sort-function-alist= to defcustom
**** ~M-n~ should prefer url at point to symbol at point
**** ~C-x C-f M-n~ calls =ffap-url-fetcher= when at URL
**** Highlight modified file buffers with =ivy-modified-buffer= face
This new face is blank by default, but you can use e.g.:
#+begin_src elisp
(custom-set-faces
 '(ivy-modified-buffer ((t (:background "#ff7777")))))
#+end_src
-----
**** Work with =enable-recursive-minibuffers=
Store the old =ivy-last= in case =ivy-read= is called while inside the
minibuffer.  Restore it after =ivy-call=.
-----
**** Allow user-specified matched candidate sorting
New defcustom =ivy-sort-matches-functions-alist=.
See [[https://github.com/abo-abo/swiper/issues/269][#269]] [[https://github.com/abo-abo/swiper/issues/265][#265]] [[https://github.com/abo-abo/swiper/issues/213][#213]].

By default, Ivy doesn't sort the matched candidates, they remain in
the same order as in the original collection. This option is the
default, since it's fast and simple.

A small problem with this approach is that we usually want prefix
matches to be displayed first. One solution to this is to input "^" to
see only the prefix matches.

Now, another solution is to can set:
#+begin_src elisp
(setq ivy-sort-matches-functions-alist
      '((t . ivy--prefix-sort)))
#+end_src

Here's another example of using this defcustom:
#+begin_src elisp
(add-to-list
     'ivy-sort-matches-functions-alist
     '(read-file-name-internal . ivy--sort-files-by-date))
#+end_src

After this, during file name completion, most recently changed files
will be ahead.
-----
**** =ivy-display-style=
Adds fancy highlighting to the minibuffer.
See [[https://github.com/abo-abo/swiper/issues/212][#212]], [[https://github.com/abo-abo/swiper/issues/217][#217]], .
-----
*** =ivy-hydra=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-ivy-hydra
:END:
**** Bind ~t~ to =toggle-truncate-lines=
See [[https://github.com/abo-abo/swiper/issues/214][#214]].
-----
**** Bind ~a~ to =ivy-read-action=
*** =ivy-switch-buffer=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-ivy-switch-buffer
:END:
**** Make ~M-o r~ rename the buffer instead of switching.
See [[https://github.com/abo-abo/swiper/issues/233][#233]].
-----
*** =counsel-locate=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-counsel-locate
:END:
**** Allow customizing locate options
See =counsel-locate-options=.
The current setting is:
#+begin_src elisp
(setq counsel-locate-options '("-i" "--regex"))
#+end_src
-----
**** Support OSX
Use =open= instead of =xdg-open=.  Modify =counsel-locate-options= for
OSX, since there =locate= doesn't support =--regex=.
-----
**** Use single quotes for the regex
See [[https://github.com/abo-abo/swiper/issues/194][#194]].
-----
**** Add initial-input argument
See [[https://github.com/abo-abo/swiper/issues/289][#289]].
-----
*** =counsel-org-tag=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-counsel-org-tag
:END:
**** Now works in agenda
See [[https://github.com/abo-abo/swiper/issues/200][#200]].
-----
*** =counsel-unicode-char=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-counsel-unicode-char
:END:
**** Add own history
*** =counsel-M-x=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-counsel-m-x
:END:
**** Add "definition" action
Use ~M-o d~ to jump to definition.
-----
**** Show =current-prefix-arg= in the prompt
See [[https://github.com/abo-abo/swiper/issues/287][#287]].
-----
*** =counsel-find-file=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-counsel-find-file
:END:
**** Input '/sudo::' goes to current directory instead of root's home
See [[https://github.com/abo-abo/swiper/issues/283][#283]].
-----
**** Fix directory validity check
See [[https://github.com/abo-abo/swiper/issues/283][#283]] [[https://github.com/abo-abo/swiper/issues/284][#284]].
-----
**** Improve TRAMP support
Selecting items after ~//~ now works properly.
-----
*** =counsel-git-grep=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-counsel-git-grep
:END:
**** Use prefix arg to specify the shell command.
Remember to use ~M-i~ to insert the current candidate into the
minibuffer.

See [[https://github.com/abo-abo/swiper/issues/244][#244]].
-----
**** Allow =counsel-git-grep= -> =ivy-occur= -> =wgrep=
Using ~C-c C-o~ (=ivy-occur=) while in =counsel-git-grep= will produce
a =wgrep=-compatible buffer.
-----
**** =ivy-occur= gives full candidates
This means that the =" | head -n 200"= speed-up isn't used and full
candidates are returned.
-----
*** =counsel--find-symbol=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-counsel--find-symbol
:END:
**** Allow to jump back with pop-tag-mark
Using ~C-.~ in:

- =counsel-describe-function=
- =counsel-describe-variable=
- =counsel-load-library=

will change the current buffer. The buffer and point can be restored
with ~M-*~ (=pop-tag-mark=).

I also recommend this binding:

#+begin_src elisp
(global-set-key (kbd "M-,") 'pop-tag-mark)
#+end_src
-----
**** Resolve the name clash better
When the symbol is both bound and fbound, prefer the fbound one,
unless the =:caller= is =counsel-describe-variable=.
-----
*** =counsel-ag=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-counsel-ag
:END:
**** Add =initial-directory=
Support alternative initial directory which helps other packages call
this function with their unique starting directory.
-----
**** Fix on Windows
Using the "--vimgrep" argument improves things.
** New Commands
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nf-new-commands
:END:
*** =ivy-occur=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-ivy-occur
:END:
Bound to ~C-c C-o~. Store the current completion session to its own
buffer.  You can have an unlimited amount of these buffers.
-----
*** =ivy-avy=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-ivy-avy
:END:
Bound to ~C-'~.

Speeds up selecting a candidate that's currently visible in the minibuffer.
-----
*** =ivy-kill-ring-save=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-ivy-kill-ring-save
:END:
Bound to ~M-w~.

When the region is active, call =kill-ring-save=.  Otherwise, store
all selected candidates to the kill ring.
-----
*** =ivy-dispatching-call=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-ivy-dispatching-call
:END:
Bound to ~C-M-o~.

This is a non-exiting version of ~M-o~ (=ivy-dispatching-done=).
-----
*** =ivy-read-action=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-ivy-read-action
:END:
Bound to ~C-M-a~. Select the current action. Don't call it yet.
-----
*** =swiper-multi=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-swiper-multi
:END:
Use =swiper= in multiple buffers.
See [[https://github.com/abo-abo/swiper/issues/182][#182]].

Basic usage tips for selecting multiple buffers:

- Use ~C-M-m~ (=ivy-call=) to add or remove one more buffer without exiting.
- Use ~C-m~ (=ivy-done=) to add one last buffer.
- Or use ~C-M-j~ (=ivy-immediate-done=) to finish without adding more buffers.
- Hold ~C-M-n~ (=ivy-next-line-and-call=) to add a lot of buffers at once.
-----
*** =swiper-mc=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-swiper-mc
:END:
Open multiple cursors at all selected candidates.
-----
*** =swiper-all=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-swiper-all
:END:
New command to launch =swiper= for all open file buffers.  Note that
this can be excruciatingly slow if you don't clean up your buffer list
often.
-----
*** =counsel-grep=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-counsel-grep
:END:
This is essentially =swiper= for huge files. It's not as smooth as
=swiper= for small files, but has a faster startup and faster matching
for files that measure in megabytes.
-----
*** =counsel-git-grep-query-replace=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-counsel-git-grep-query-replace
:END:
Bound to ~M-q~. Perform =query-replace= on all matches in all buffers.
-----
*** =counsel-jedi=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-counsel-jedi
:END:
Complete Python symbols using Jedi.
-----
*** =counsel-cl=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-counsel-cl
:END:
Complete Common Lisp symbols using SLIME.
-----
*** =counsel-yank-pop=
:PROPERTIES:
:CUSTOM_ID: 0-7-0-nc-counsel-yank-pop
:END:
Give completion for inserting from the kill ring.
See =counsel-yank-pop-truncate= defcustom and [[https://github.com/abo-abo/swiper/issues/218][#218]].
-----
* 0.8.0
:PROPERTIES:
:CUSTOM_ID: 0.8.0
:END:
-----
** Package rename
:PROPERTIES:
:CUSTOM_ID: 0-8-0-package-rename
:END:
Due to popular demand, =swiper-0.7.0= is succeeded by =ivy-0.8.0= in GNU
ELPA. The contents of the package don't change, only the name. Make
sure to remove the =~/.emacs.d/elpa/swiper-0.7.0= directory if you
have it and ~M-x~ =package-install ivy=.
** Documentation
:PROPERTIES:
:CUSTOM_ID: 0-8-0-documentation
:END:
HTML documentation is available at http://oremacs.com/swiper/.

Texinfo documentation is in doc/ivy.texi.

The HTML file shouldn't be in this repository to avoid bloat, instead
it's in the gh-pages branch at
https://github.com/abo-abo/swiper/tree/gh-pages.
** Fixes
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fixes
:END:
*** =ivy-read=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-read
:END:
**** Fix recursive minibuffer exit with ~C-g~
Make it so e.g. ~C-h f C-h v C-g~ goes back to the =describe-function= selection.
-----
**** Ensure the return result
In some cases, =read-from-minibuffer= will return the whole minibuffer
contents (i.e. all available candidates). Return =ivy--current= instead.
-----
**** Properly support matching ignoring order
See [[https://github.com/abo-abo/swiper/issues/296][#296]] and [[https://github.com/abo-abo/swiper/issues/329][#329]].
-----
**** Insert intermediate candidates during async completions
See [[https://github.com/abo-abo/swiper/issues/340][#340]].
-----
**** Initialize =ivy-last= to empty state
See [[https://github.com/abo-abo/swiper/issues/352][#352]].
-----
**** Fix extra actions for =completing-read=
See [[https://github.com/abo-abo/swiper/issues/337][#337]].
-----
**** Support a list of symbols as collection
See [[https://github.com/abo-abo/swiper/issues/375][#375]].
-----
**** Define =setq-local= and =defvar-local= unless defined
With this commit, Ivy works on emacs-24.2.
See [[https://github.com/abo-abo/swiper/issues/415][#415]].
-----
**** Make ~M-o~ not modify the action
See [[https://github.com/abo-abo/swiper/issues/454][#454]].
-----
**** Make sure user keybindings are respected
See [[https://github.com/abo-abo/swiper/issues/466][#466]].
-----
**** Fix =read-file-name= with a specified dir
See [[https://github.com/abo-abo/swiper/issues/475][#475]].
-----
**** Don't highlight the match in the file part
See [[https://github.com/abo-abo/swiper/issues/483][#483]].
-----
**** Add a few tests for alists
-----
*** =ivy-occur=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-occur
:END:
**** Fix =default-directory=
This way, =next-error= etc will work properly.
-----
*** =ivy--resize-minibuffer-to-fit=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy--resize-minibuffer-to-fit
:END:
**** Fix for small delta
See [[https://github.com/abo-abo/swiper/issues/339][#339]].
-----
**** Check =frame-root-window-p=
See [[https://github.com/abo-abo/swiper/issues/380][#380]].
-----
*** =ivy-completing-read=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-completing-read
:END:
**** Use =completing-read-default= for tmm
See [[https://github.com/abo-abo/swiper/issues/316][#316]].
-----
*** =ivy--regex-plus=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy--regex-plus
:END:
**** Recognize ! at the beginning of the str
See [[https://github.com/abo-abo/swiper/issues/318][#318]].
-----
**** Prettify a bit
See [[https://github.com/abo-abo/swiper/issues/344][#344]].
-----
**** Don't consider =\\(?...\)= a group
See [[https://github.com/abo-abo/swiper/issues/393][#393]].
-----
*** =ivy--get-window=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy--get-window
:END:
**** Always return a valid window
Even if =state= is invalid.
-----
*** =ivy--recompute-index=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy--recompute-index
:END:
**** Update =cl-position= logic
See [[https://github.com/abo-abo/swiper/issues/207][#207]].
-----
*** =ivy-reverse-i-search=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-reverse-i-search
:END:
**** Fix due to recursive update
See [[https://github.com/abo-abo/swiper/issues/323][#323]].
-----
*** =ivy--reset-state=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy--reset-state
:END:
**** Don't null =initial-input=
This is specifically for ='read-file-name-internal= collection.  The
input needs to be set to nil for e.g. =rgrep=, which supplies the
*absolute* path as =initial-input=, resulting in a mess.

For now, don't set input to nil if =:action= was passed to =ivy-read=.
See [[https://github.com/abo-abo/swiper/issues/336][#336]].
-----
**** Don't deactivate region
See [[https://github.com/abo-abo/swiper/issues/377][#377]].
-----
*** =ivy-completion-in-region=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-completion-in-region
:END:
**** Use =completion-all-completions=
See [[https://github.com/abo-abo/swiper/issues/341][#341]].
-----
**** Optimize for 1 candidate
When there's only one candidate, call the action immediately.
-----
**** Add feedback for 1 candidate
When the sole completion is the same as the input, notify the user.
See [[https://github.com/abo-abo/swiper/issues/350][#350]].
-----
**** Bind =completion-ignore-case=
It's convenient to have it the same value as =case-fold-search=.
-----
*** =ivy-read-action=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-read-action
:END:
**** Give enough minibuffer space
See [[https://github.com/abo-abo/swiper/issues/402][#402]].
-----
**** Allow to customize the action hint formatter
See [[https://github.com/abo-abo/swiper/issues/469][#469]].
-----
*** =ivy-count-format=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-count-format
:END:
**** Fix for nil value
See [[https://github.com/abo-abo/swiper/issues/349][#349]].
-----
*** =ivy-switch-buffer=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-switch-buffer
:END:
**** Don't fall back to =switch-to-buffer=
See [[https://github.com/abo-abo/swiper/issues/410][#410]].
-----
*** =ivy-next-history-element=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-next-history-element
:END:
**** No "\\_<" for dynamic-collection
"\\_<" regex is Emacs-specific and should only be done if
=:dynamic-collection= is nil.  It is nil for =counsel-git-grep= with
repositories < 20000 lines, but non-nil for larger ones.

Fixes [[https://github.com/abo-abo/swiper/issues/409][#409]].
-----
*** =ivy-occur-press=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-occur-press
:END:
**** Pulse no longer
Repeated pulses within a short time span resulted in horrible window
flickering.
-----
*** =ivy-resume=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-resume
:END:
**** Add a guard against null =:action=
-----
*** =ivy-avy=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-avy
:END:
**** Make ~C-g~ cancel gracefully
See abo-abo/avy[[https://github.com/abo-abo/swiper/issues/140][#140]].
-----
*** =ivy-dispatching-done=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-ivy-dispatching-done
:END:
Allow to exit with no candidates.
-----
*** =swiper=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-swiper
:END:
**** Improve for multiple occurrences on one line
See [[https://github.com/abo-abo/swiper/issues/314][#314]].
-----
**** Fix "backward" search
When none of the previous candidates after the point match the current
input, instead of returning 0, return the index of the last matching
candidate.  This is a good choice, because that candidate is the
closest to the point of the initial search start.

See [[https://github.com/abo-abo/swiper/issues/319][#319]].
-----
**** Return point
See [[https://github.com/abo-abo/swiper/issues/370][#370]].
-----
**** Update =regexp-search-ring=
See [[https://github.com/abo-abo/swiper/issues/89][#89]].
-----
**** Always remove '(field) text property
Allows to search better in modes for shell interaction.
-----
*** =swiper-font-lock-ensure=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-swiper-font-lock-ensure
:END:
**** Add modes
Add bongo-library-mode, bongo-playlist-mode, sauron-mode.

See [[https://github.com/abo-abo/swiper/issues/19][#19]].
-----
**** Don't fail when font-lock is off
See [[https://github.com/abo-abo/swiper/issues/400][#400]].
-----
*** =swiper--multi-candidates=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-swiper--multi-candidates
:END:
**** Add check for =make-string=
See [[https://github.com/abo-abo/swiper/issues/481][#481]].
-----
*** =counsel--async-sentinel=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-counsel--async-sentinel
:END:
**** Fix issue with =ivy--regex-ignore-order=
See [[https://github.com/abo-abo/swiper/issues/342][#342]].
-----
**** Re-display when no cands
**** Recognize error codes other than 1
See [[https://github.com/abo-abo/swiper/issues/394][#394]].
-----
*** =counsel-git=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-counsel-git
:END:
**** Fix window selection.
Use =with-ivy-window=, so that each new file chosen with e.g. ~C-M-n~ is
selected in the same window.
-----
*** =counsel-recoll=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-counsel-recoll
:END:
**** Add =:unwind=
See [[https://github.com/abo-abo/swiper/issues/403][#403]].
-----
*** compilation warnings
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-compilation-warnings
:END:
See [[https://github.com/abo-abo/swiper/issues/324][#324]].
-----
** New Features
:PROPERTIES:
:CUSTOM_ID: 0-8-0-fx-new-features
:END:
*** =ivy-read=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-read
:END:
**** Use =flx= for highlighting fuzzy matches
See [[https://github.com/abo-abo/swiper/issues/207][#207]].
-----
**** Simplify the signature for =:dynamic-collection= functions
When given =:dynamic-collection=, assume the collection function only
needs one argument - the string input.
-----
**** Modify ~M-n~ prediction when region is active
When the region is active and ~M-n~ is called, insert the region
contents into the minibuffer and deactivate the region. The region
deactivation is done for =swiper=, to make it easier to search for
multiple words or a subword.
-----
**** Allow to compose collections
***** Example 1: async collection
Stack =recentf= on top of =counsel-locate=:

#+begin_src elisp
(defun small-test ()
  (cl-subseq recentf-list 0 10))

(ivy-set-sources
 'counsel-locate
 '((small-test)
   (original-source)))
#+end_src

Here, (original-source) represents the async candidates of
=counsel-locate=. All extra sources are static - each function is called
once to generate a list of strings, which will be filtered later.

The order matters, so you can have e.g.:

#+begin_src elisp
(ivy-set-sources
 'counsel-locate
 '((original-source)
   (small-test)))
#+end_src

See [[https://github.com/abo-abo/swiper/issues/373][#373]].
-----
***** Example 2: sync collection
#+begin_src elisp
(defun my-extra-source ()
  (append
   (when (eq 'Git (vc-backend (buffer-file-name)))
     (list "git1" "git2" "git3"))
   (when (file-exists-p "doc/Changelog.org")
     (list (propertize "doc/Changelog.org" 'face '(:background "red"))))))

(defun my-find-file ()
  (interactive)
  (ivy-read "Find file: " 'read-file-name-internal
            :action (lambda (x)
                      (with-ivy-window
                        (find-file (expand-file-name x ivy--directory))))
            :require-match 'confirm-after-completion
            :history 'file-name-history
            :caller 'my-find-file))

(ivy-set-sources
 'my-find-file
 '((my-extra-source)
   (original-source)))
#+end_src

The function =my-find-file= knows nothing about the extra source, it's
only purpose is to introduce a =:caller= to attach things to, as to not
to mess up e.g. =counsel-find-file=.

The function =my-extra-source= gets called once in =ivy-read= via
=ivy--reset-state=. It takes no args and returns a list of strings,
possibly empty.
-----
**** Improve documentation UI
Bind ~C-h m~ to =ivy-help=.

=ivy-help-file= is a new defvar pointing to the ivy-help.org file.

Bind ~D~ in =hydra-ivy= to go to hydra's definition.

See [[https://github.com/abo-abo/swiper/issues/376][#376]] and [[https://github.com/abo-abo/swiper/issues/379][#379]].
-----
**** Add ignore pattern toggling
~C-c C-a~ is bound to =ivy-toggle-ignore= - a new command to toggle ignore
patterns (user-configured filtering). If the ignore patterns are
enabled and there are zero candidates after ignoring, display the ones
that match the current text. This feature currently works for
=ivy-switch-buffer= and =counsel-find-file=.

See [[https://github.com/abo-abo/swiper/issues/369][#369]].
-----
*** =ivy-mode=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-mode
:END:
**** Set =completion-in-region-function=
See [[https://github.com/abo-abo/swiper/issues/331][#331]].
-----
**** Improve ~M-n~ for ='read-file-name-internal=
-----
*** =ivy-set-occur=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-set-occur
:END:
Allows to customize =ivy-occur= per-command.
-----
**** Add custom occur for =ivy-switch-buffer=
See [[https://github.com/abo-abo/swiper/issues/438][#438]] and [[https://github.com/abo-abo/swiper/issues/440][#440]].
-----
*** =ivy-occur-mode=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-occur-mode
:END:
**** New commands on ~j~, ~k~, ~c~
(ivy-occur-toggle-calling): New command bound to ~c~.
(ivy-occur-next-line): New command bound to ~j~.
(ivy-occur-previous-line): New command bound to ~k~.

This makes =ivy-occur= much more convenient, instead of ~gjgjgjg~, just
~cjjj~. Especially good for commands that change the contents of the
other window, like =describe-function= or =counsel-git-grep=.

Example:

- ~C-h f~ (=describe-funtion=)
- =run= (=self-insert-command=)
- ~C-c C-o~ (=ivy-occur=); ~C-o u~ also works.
- ~cjjjjkkkk~
-----
**** New command =ivy-occur-revert-buffer= on ~g~
Does what e.g. =revert-buffer= does for *Help* buffers.

Has special handling for =counsel-git-grep=, =counsel-ag= and
=counsel-grep=: will run the shell command once more and reflect the
updates in files.

Move =ivy-occur-press= from ~g~ to ~f~.
-----
**** Improve the feedback for ~j~ and ~k~
The overlays will be more responsive now.
-----
*** =ivy-re-builders-alist=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-re-builders-alist
:END:
**** Allow =this-command= to be a key
Example:
#+begin_src elisp
(defun asdf ()
  (interactive)
  (completing-read "prompt: " '("abc" "abcd" "def")))

(global-set-key (kbd "C-c t") 'asdf)

(setq ivy-re-builders-alist
      '(
        (asdf . ivy--regex-fuzzy)
        (t . ivy--regex-plus)))
#+end_src
This is useful for commands that you didn't write. For new commands
that you write, consider using =ivy-read= and =:caller=.

See [[https://github.com/abo-abo/swiper/issues/330][#330]].
-----
*** =ivy-set-actions=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-set-actions
:END:
**** Call with =t= to affect all commands
Example:

#+begin_src elisp
(ivy-set-actions
 t
 '(("i" insert "insert")))
#+end_src

Now an "insert" action will be available for all =ivy-read= sessions
when pressing ~M-o~.

See [[https://github.com/abo-abo/swiper/issues/337][#337]].
-----
*** =ivy-faces=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-faces
:END:
New defcustom group.
See [[https://github.com/abo-abo/swiper/issues/389][#389]].
-----
*** =ivy-flx-limit=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-flx-limit
:END:
New variable. Configure when =flx= is used.
See [[https://github.com/abo-abo/swiper/issues/207][#207]].
-----
*** =ivy-inhibit-action=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-inhibit-action
:END:
New variable. See [[https://github.com/abo-abo/swiper/issues/363][#363]].
-----
*** =ivy-do-completion-in-region=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-do-completion-in-region
:END:
New defcustom. See [[https://github.com/abo-abo/swiper/issues/367][#367]].
-----
*** =ivy-fixed-height-minibuffer=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-fixed-height-minibuffer
:END:
New defcustom.

When non nil, fix the height of the minibuffer during ivy completion
at =ivy-height=. This effectively sets the minimum height at this level
and tries to ensure that it does not change depending on the number of
candidates.

See [[https://github.com/abo-abo/swiper/issues/353][#353]].
-----
*** =ivy-set-display-transformer=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-set-display-transformer
:END:
New API function.

Now used by =switch-to-buffer= and =read-file-name=.

See [[https://github.com/abo-abo/swiper/issues/399][#399]].
-----
*** =ivy-ignore-buffers=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-ignore-buffers
:END:
New defcustom similar to =ido-ignore-buffers=.

See [[https://github.com/abo-abo/swiper/issues/382][#382]] and [[https://github.com/abo-abo/swiper/issues/366][#366]].
-----
*** =ivy-add-newline-after-prompt=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-add-newline-after-prompt
:END:
New defcustom.

See [[https://github.com/abo-abo/swiper/issues/451][#451]].
-----
*** =ivy-switch-buffer=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-switch-buffer
:END:
**** Add virtual views
=ivy-views= variable stores pre-defined views. Allows to set a window
configuration with many buffers from =ivy-switch-buffer=.

How to use: just set =ivy-views= appropriately. An example value is
provided (but nulled, so that it's empty initially).
-----
*** =ivy-use-ignore-default=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-ivy-use-ignore-default
:END:
New defcustom

See [[https://github.com/abo-abo/swiper/issues/477][#477]].
-----
*** =swiper=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-swiper
:END:
**** Improve =swiper-query-replace=
To replace a symbol with a similar symbol,

1. Press ~C-s M-n~ for =swiper= and select the symbol at point as input.
2. Press ~M-q~ for =swiper-query-replace=
3. Press ~M-n~ to yank the symbol to replace.
4. Edit the replacement and ~RET~.

Here step-3 was modified to yank e.g. "symbol" instead of
"\_<symbol\_>" previously.
-----
*** =swiper-font-lock-exclude=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-swiper-font-lock-exclude
:END:
New variable for major modes that misbehave with =font-lock-ensure=.
See [[https://github.com/abo-abo/swiper/issues/346][#346]].
-----
*** =swiper-all=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-swiper-all
:END:
**** New auto-updates position
See [[https://github.com/abo-abo/swiper/issues/401][#401]].
-----
*** =counsel-mode=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-mode
:END:
A minor-mode that remaps built-in functions that have counsel
replacements available.

See [[https://github.com/abo-abo/swiper/issues/414][#414]].
-----
**** Allow use of describe-prefix-bindings
See [[https://github.com/abo-abo/swiper/issues/441][#441]].
-----
*** =counsel-find-file=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-find-file
:END:
**** Add =initial-input=
See [[https://github.com/abo-abo/swiper/issues/336][#336]].
-----
**** Change tramp prompt from "Find File: " to "user@host: "
**** Bind =counsel-up-directory= to ~C-DEL~
New function that moves up to the parent directory and at the same
time preselects the current directory. This is useful for moving up
and down a file tree quickly.

See [[https://github.com/abo-abo/swiper/issues/343][#343]].
-----
**** Customize =M-n= action
This feature allows to quickly visit Github issues from either
=magit-commit-mode= or from a version-controlled file. The point has to
be at the "#" char in e.g. "[[https://github.com/abo-abo/swiper/issues/123][#123]]", that represents an issue.

It's possible to customize =ivy-ffap-url-functions= to do a similar
thing for places other than Github.

The ~C-x C-f M-n~ key binding will work better with =counsel-find-file=,
for plain =find-file= it will open a =dired= buffer in addition to opening
the URL.
-----
**** Can un-ignore dotfiles with a leading dot input
When =ivy-text= starts with a dot, don't use
=counsel-find-file-ignore-regexp=. The generic way to do this is with
~C-c C-a~ (=ivy-toggle-ignore=), but this is faster and more convenient.

See [[https://github.com/abo-abo/swiper/issues/408][#408]].
-----
**** Bind ~M-o f~ to =find-file-other-window=
**** Correctly expand file name at point
See [[https://github.com/abo-abo/swiper/issues/430][#430]].
-----
**** Add display transformer
See [[https://github.com/abo-abo/swiper/issues/458][#458]].
-----
**** Add magic slash that changes the directory
Update to the behavior: the slash ("/") will enter a directory even if
its name isn't completely typed out if either:

1. It's the only candidate.
2. The candidate index isn't 0, i.e. "C-n" has been typed at least once.
3. The input isn't "/".

The above rules still allow to keep the old behavior with "//" moving
to root and "/ssh:" opening tramp.

This is an experimental feature, please report if it breaks someone's
workflow.

See [[https://github.com/abo-abo/swiper/issues/321][#321]] and [[https://github.com/abo-abo/swiper/issues/480][#480]].
-----
*** =counsel-git-grep=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-git-grep
:END:
**** Bind ~C-c C-m~ to =counsel-git-grep-switch-cmd=
The initial command always runs on all files.

To run only on *.el files, ~C-c C-m~ followed by ~M-i~ =-- *.el=.
To run on *.c and *.h files, ~C-c C-m~ followed by ~M-i~ =-- *.c *.h=.
To switch to all files again, ~C-c C-m~ and select the appropriate
entry.

See [[https://github.com/abo-abo/swiper/issues/420][#420]].
-----
*** =counsel-locate=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-locate
:END:
**** counsel-locate-cmd
New defcustom that replaces =counsel-locate-options=.

See [[https://github.com/abo-abo/swiper/issues/385][#385]].
-----
**** counsel-locate-cmd-mdfind
New function.
See [[https://github.com/abo-abo/swiper/issues/390][#390]].
-----
**** counsel-locate-cmd-es
New function.
See [[https://github.com/abo-abo/swiper/issues/426][#426]].
-----
*** =counsel-yank-pop=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-yank-pop
:END:
**** Truncate during display
During the completion, only the context around the match will be shown.
By default, the context is +2 lines above and +2 lines below the match.
It can be adjusted with =counsel-yank-pop-truncate-radius=.
Additionally, =ivy-height= is temporarily bound to 5 during completion.
This way, the maximum minibuffer height should be 1+4*5=21 lines.

See [[https://github.com/abo-abo/swiper/issues/315][#315]].
-----
*** =counsel-unicode-char=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-unicode-char
:END:
Display hex codes in left column.
-----
*** =counsel-rhythmbox=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-rhythmbox
:END:
**** Preselect the current song
-----
*** =counsel-ag=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-ag
:END:
**** =counsel-ag-base-command=
Allows the command run by =counsel-ag-function= to be customized. There
are several reasons to allow this: The vimgrep option is a recent
addition; on windows it's more convenient to use pt; and the user
might want to customize ignored files.

Standard value:
#+begin_src elisp
(setq counsel-ag-base-command "ag --nocolor --nogroup %s -- .")
#+end_src

See [[https://github.com/abo-abo/swiper/issues/335][#335]].
-----
**** Add dir prompt for ~C-u~
See [[https://github.com/abo-abo/swiper/issues/429][#429]].
-----
**** Add =counsel-ag-map=
See [[https://github.com/abo-abo/swiper/issues/462][#462]].
-----
*** =counsel-async-split-string-re=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-async-split-string-re
:END:
New defcustom.
-----
*** =counsel--async-cmd=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel--async-cmd
:END:
**** Add optional exit-code table
This argument can be used to associate exit codes with the underlying
reason. Used in counsel-ag-function to signal that an exit code of 1
means that no matches were found.

See [[https://github.com/abo-abo/swiper/issues/421][#421]].
-----
*** =counsel-prompt-function=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-prompt-function
:END:
New defcustom

See [[https://github.com/abo-abo/swiper/issues/424][#424]] and [[https://github.com/abo-abo/swiper/issues/425][#425]].
-----
*** =counsel-grep=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-grep
:END:
**** Reveal outlines
Just like =swiper=.
-----
**** Should pick candidates closest to point
Fixes the algorithm selecting the first matching candidate in case
there are 0 matching candidates following point. Now the last matching
candidate will be selected, resulting in less scrolling.
-----
**** Speed up x40 times
The default shell command will not use =--ignore-case= switch for
=grep=. It's a bit less convenient, but results in a huge speed-up.
-----
*** =counsel-M-x=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-counsel-m-x
:END:
**** Add help action
Bound to ~M-o h~ by default.

See [[https://github.com/abo-abo/swiper/issues/452][#452]].
** New Commands
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nf-new-commands
:END:
*** =counsel-tmm=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-tmm
:END:
Completion for the menu bar items. For example:

=counsel-tmm= -> =Options= -> =Set Default Font...=.

Thanks to completion, the latter stages of the chain would look like: =op= ~RET~ =set= ~RET~.
-----
*** =counsel-imenu=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-imenu
:END:
Jump to a buffer position indexed by imenu.
-----
*** =counsel-decbinds=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-decbinds
:END:
Show a list of all defined keys, and their definitions. Describe the
selected candidate.
See [[https://github.com/abo-abo/swiper/issues/332][#332]].
-----
*** =counsel-list-processes=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-list-processes
:END:
Offer completion for =process-list=

The default action deletes the selected process.  An extra action
allows to switch to the process buffer.

See [[https://github.com/abo-abo/swiper/issues/357][#357]] and [[https://github.com/abo-abo/swiper/issues/398][#398]].
-----
*** =ivy-switch-buffer-other-window=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-ivy-switch-buffer-other-window
:END:
Remap =switch-to-buffer-other-window= to =ivy-switch-buffer-other-window= for =ivy-mode=.

See [[https://github.com/abo-abo/swiper/issues/361][#361]].
-----
*** =counsel-git-stash=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-git-stash
:END:
Search through all available git stashes.

See [[https://github.com/abo-abo/swiper/issues/374][#374]].
-----
*** =counsel-git-log=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-git-log
:END:
Call the =git log --grep= shell command and search through the output.
-----
*** =counsel-pt=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-pt
:END:
Grep for a string in the current directory using pt.

See [[https://github.com/abo-abo/swiper/issues/434][#434]].
-----
*** =counsel-linux-app=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-linux-app
:END:
Launch a Linux desktop application, similar to Alt-<F2>.

See [[https://github.com/abo-abo/swiper/issues/446][#446]].
-----
*** =counsel-ace-link=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-ace-link
:END:
Ivy completion for =ace-link=.
-----
*** =counsel-esh-history=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-esh-history
:END:
Browse Eshell history.

See [[https://github.com/abo-abo/swiper/issues/459][#459]].
-----
*** =counsel-shell-history=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-shell-history
:END:
Browse shell history.
-----
*** =counsel-grep-or-swiper=
:PROPERTIES:
:CUSTOM_ID: 0-8-0-nc-counsel-grep-or-swiper
:END:
New command: automatically use =swiper= for smaller buffers and
=counsel-grep= for larger buffers.

Adjust with:
#+begin_src elisp
(setq counsel-grep-swiper-limit 300000)
#+end_src

By default, the splitting predicate is 300K bytes in a file.
-----
#+BEGIN_EXPORT html
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
#+END_EXPORT

